version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: pasa_la_pagina_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer_mysql
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
